# Generated by Django 4.2 on 2023-07-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='idpro',
            new_name='idprorwt',
        ),
    ]
