# Generated by Django 4.2 on 2023-07-11 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0001_changed_my_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precommande',
            fields=[
                ('idprecom', models.AutoField(primary_key=True, serialize=False)),
                ('idpro', models.IntegerField()),
                ('idclt', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('nbrjour', models.IntegerField(default=30)),
                ('etat', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'precommande',
            },
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=5, max_digits=100, null=True),
        ),
    ]
