# Generated by Django 4.2 on 2023-07-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0002_changed_my_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='precommande',
            name='description',
            field=models.TextField(default='description du  produit'),
        ),
        migrations.AddField(
            model_name='precommande',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=10.2, max_digits=10),
        ),
    ]
