# Generated by Django 4.2 on 2023-07-02 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0002_rename_idpro_product_idprorwt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='idu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monespace.users'),
        ),
    ]
