# Generated by Django 4.2 on 2023-07-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0003_changed_my_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('idpcompt', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('idclt', models.IntegerField()),
                ('etat', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'compte',
            },
        ),
    ]
