# Generated by Django 4.2 on 2023-07-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0003_product_idu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('ident', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('mdpent', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'entreprise',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
