# Generated by Django 4.2 on 2023-07-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0004_entreprise_delete_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entreprise',
            table='orbitentreprise',
        ),
    ]
