# Generated by Django 4.2 on 2023-07-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0007_remove_dmdcredit_idclt_dmdcredit_nomclt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmdcredit',
            name='idclt',
            field=models.IntegerField(default=1),
        ),
    ]
