# Generated by Django 4.2 on 2023-07-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0008_dmdcredit_idclt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idpro', models.AutoField(primary_key=True, serialize=False)),
                ('mimage', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
