# Generated by Django 4.2 on 2023-07-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0009_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idcom', models.AutoField(primary_key=True, serialize=False)),
                ('idlct', models.IntegerField()),
                ('idpro', models.IntegerField()),
                ('action', models.CharField(default='direct', max_length=100)),
            ],
            options={
                'db_table': 'commande',
            },
        ),
    ]
