# Generated by Django 4.2 on 2023-07-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0011_alter_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='adresseu',
            field=models.CharField(max_length=15, null=True, verbose_name='Votre Adresse'),
        ),
        migrations.AlterField(
            model_name='users',
            name='emailu',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name=' Votre Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.FileField(upload_to='photos', verbose_name='Profil'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mdpu',
            field=models.CharField(max_length=128, null=True, verbose_name='Votre  Mot de Passse'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nompreu',
            field=models.CharField(max_length=100, null=True, verbose_name='Votre  Nom'),
        ),
        migrations.AlterField(
            model_name='users',
            name='postu',
            field=models.CharField(max_length=128, null=True, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='users',
            name='teleu',
            field=models.CharField(max_length=15, null=True, verbose_name='Votre Télephone'),
        ),
    ]
